# Set up Cygwin. Source: https://github.com/egor-tensin/setup-cygwin
name: compile_cygwin

on: [push]

jobs:
  setup_cygwin:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

    steps:
      - name: setup_cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x86
          packages: git mingw64-i686-gcc-core mingw64-i686-gcc-g++ mingw64-i686-winpthreads make curl mingw64-i686-openssl
      - name: Download_libffcall
        run: curl -O https://ftp.gnu.org/gnu/libffcall/libffcall-2.4.tar.gz
      - name: Extract_libffcall
        run: tar xvf libffcall-2.4.tar.gz
      - name: Build_libffcall
        run: |
             cd libffcall-2.4
             ./configure --enable-static --enable-shared=no  --build=i686-unknown-cygwin --host=i686-w64-mingw32 --prefix=$HOME/libffcall
             make
             make install
      - name: Download_libsigsegv
        run: curl -O https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.14.tar.gz
      - name: Extract_libffcall
        run: tar xvf libsigsegv-2.14.tar.gz
      - name: Build_libsigsegv
        run: |
             cd libsigsegv-2.14
             ./configure --build=i686-unknown-cygwin --host=i686-w64-mingw32 --prefix=$HOME/libsigsegv
             make
             make install
      - name: Download_libiconv
        run: curl -O https://ftp.gnu.org/gnu/libiconv/libiconv-1.16.tar.gz
      - name: Extract_libiconv
        run: tar xvf libiconv-1.16.tar.gz
      - name: Build_libiconv
        run: |
             cd libiconv-1.16
             ./configure --build=i686-unknown-cygwin --host=i686-w64-mingw32 --enable-static --enable-shared=no --prefix=$HOME/libiconv
             make
             make install
      - name: Checkout_git
        run: git clone --depth 1 https://github.com/daute/clisp.git
      - name: Configure_clisp
        run: |
             cd clisp
             CFLAGS=-Wl,--stack,8388608 ./configure --config --host=i686-w64-mingw32 --with-debug --disable-threads --with-libffcall-prefix=$HOME/libffcall --with-libsigsegv-prefix=$HOME/libsigsegv --with-libiconv-prefix=$HOME/libiconv --with-openssl build

      - name: Compile_clisp
        run: |
             cd clisp/build
             cp /usr/i686-w64-mingw32/sys-root/mingw/bin/libwinpthread-1.dll .
             make lisp.exe
             peflags --stack-reserve lisp.exe
             peflags --stack-reserve=0x800000 lisp.exe
             peflags --stack-reserve lisp.exe
             make boot
             cp /usr/i686-w64-mingw32/sys-root/mingw/bin/libwinpthread-1.dll boot
             make --trace base VERBOSE=1
             cp /usr/i686-w64-mingw32/sys-root/mingw/bin/libwinpthread-1.dll base
             find /home/runneradmin/clisp
             tar -cf /tmp/clisp.tar .

      - uses: actions/upload-artifact@v3
        with:
          path: C:\\tools\\cygwin\\tmp\\clisp.tar
