# Set up Cygwin. Source: https://github.com/egor-tensin/setup-cygwin
name: compile_cygwin

on: [push]

jobs:
  setup_cygwin:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        
    steps:
      - name: setup_cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x86
          packages: git mingw64-i686-gcc-core make git curl
      - name: Download_libffcall
        run: curl https://ftp.gnu.org/gnu/libffcall/libffcall-2.4.tar.gz --output libffcall-2.4.tar.gz
      - name: Extract_libffcall
        run: tar xvf libffcall-2.4.tar.gz
      - name: Build_libffcall
        run: |
             cd libffcall-2.4
             ./configure configure --enable-static --enable-shared=no --host=i686-w64-mingw32 --prefix=$HOME/libffcall
             make
             make install
      - name: Checkout_git
        run: git clone --depth 1 https://github.com/daute/clisp.git
      - name: configure
        run: |
             cd clisp
             ./configure --config --host=i686-w64-mingw32 --enable-portability --ignore-absence-of-libsigsegv --disable-threads --with-libffcall-prefix=$HOME/libffcall build

      - name: compile
        run: |
             cd clisp/build
             make
