# Set up Cygwin. Source: https://github.com/egor-tensin/setup-cygwin
name: compile_cygwin

on: [push]

jobs:
  setup_cygwin:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

    steps:
      - name: setup_cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x86
          packages: git mingw64-i686-gcc-core mingw64-i686-gcc-g++ make curl
      - name: Download_libffcall
        run: curl -O https://ftp.gnu.org/gnu/libffcall/libffcall-2.4.tar.gz
      - name: Extract_libffcall
        run: tar xvf libffcall-2.4.tar.gz
      - name: Build_libffcall
        run: |
             cd libffcall-2.4
             ./configure configure --enable-static --enable-shared=no  --build=i686-unknown-cygwin --host=i686-w64-mingw32 --prefix=$HOME/libffcall
             make
             make install
      - name: Download_libsigsegv
        run: curl -O https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.14.tar.gz
      - name: Extract_libffcall
        run: tar xvf libsigsegv-2.14.tar.gz
      - name: Build_libsigsegv
        run: |
             cd libsigsegv-2.14
             ./configure configure --build=i686-unknown-cygwin --host=i686-w64-mingw32 --prefix=$HOME/libsigsegv
             make
             make install
      - name: Checkout_git
        run: git clone --depth 1 https://github.com/daute/clisp.git
      - name: Configure_clisp
        run: |
             cd clisp
             ./configure --config --host=i686-w64-mingw32 --enable-portability --disable-threads --with-libffcall-prefix=$HOME/libffcall --with-libsigsegv-prefix=$HOME/libsigsegv build

      - name: Compile_clisp
        run: |
             cd clisp/build
             make lisp.exe
             find /home/runneradmin/clisp
             tar -cf /tmp/clisp.tar .

      - uses: actions/upload-artifact@v3
        with:
          path: C:\\tools\\cygwin\\tmp\\clisp.tar
